<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>12</LangVersion>
		<Version>1.5.0</Version>
		<Authors>Sandro Hanea</Authors>
		<Description>Cross-platform dotnet bindings for Whisper.</Description>
		<PackageProjectUrl>https://github.com/sandrohanea/whisper.net</PackageProjectUrl>
		<RepositoryUrl>https://github.com/sandrohanea/whisper.net</RepositoryUrl>
		<RepositoryType>GIT</RepositoryType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<Platforms>x64</Platforms>
		<Configurations>Debug;Release</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE" Pack="true" PackagePath="" />
		<None Include="..\readme.md" Pack="true" PackagePath="" />
	</ItemGroup>

	<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
		<TargetFrameworks>net8.0</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX')) Or $([MSBuild]::IsOSPlatform('Windows'))">
		<TargetFrameworks>
      net8.0;net6.0;netstandard2.0;net8.0-ios;net8.0-tvos;net8.0-maccatalyst
    </TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|x64'">
	  <DebugType>embedded</DebugType>
	  <IsTrimmable>True</IsTrimmable>
	  <IsAotCompatible>True</IsAotCompatible>
	  <WarningLevel>7</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0|x64'">
	  <DebugType>embedded</DebugType>
	  <IsTrimmable>True</IsTrimmable>
	  <IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|x64'">
	  <DebugType>embedded</DebugType>
	  <IsTrimmable>True</IsTrimmable>
	  <IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|x64'">
	  <DebugType>embedded</DebugType>
	  <IsTrimmable>True</IsTrimmable>
	  <IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-tvos|x64'">
	  <DebugType>embedded</DebugType>
	  <IsTrimmable>True</IsTrimmable>
	  <IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-maccatalyst|x64'">
	  <DebugType>embedded</DebugType>
	  <IsTrimmable>True</IsTrimmable>
	  <IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|x64'">
	  <DebugType>embedded</DebugType>
	  <IsTrimmable>True</IsTrimmable>
	  <IsAotCompatible>True</IsAotCompatible>
	  <WarningLevel>7</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0|x64'">
	  <DebugType>embedded</DebugType>
	  <IsTrimmable>True</IsTrimmable>
	  <IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|x64'">
	  <DebugType>embedded</DebugType>
	  <IsTrimmable>True</IsTrimmable>
	  <IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|x64'">
	  <DebugType>embedded</DebugType>
	  <IsTrimmable>True</IsTrimmable>
	  <IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-tvos|x64'">
	  <DebugType>embedded</DebugType>
	  <IsTrimmable>True</IsTrimmable>
	  <IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-maccatalyst|x64'">
	  <DebugType>embedded</DebugType>
	  <IsTrimmable>True</IsTrimmable>
	  <IsAotCompatible>True</IsAotCompatible>
	</PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.IO.Compression" Version="4.3.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\whisper.cpp\.build\tasks\whisper.vcxproj" />
  </ItemGroup>

</Project>